#+TITLE: Code Complete
#+HUGO_BASE_DIR: ~/txt/blog/
#+HUGO_SECTION: en/posts
:PROPERTIES:
:EXPORT_FILE_NAME: code-complete-notes
:EXPORT_TITLE: Code Complete Notlarım
:HUGO_BASE_DIR: ~/txt/blog/
:HUGO_SECTION: en/posts
:EXPORT_AUTHOR: savolla
:END:

* bölüm 1 - yazılım inşasına giriş
+ yazara göre, bu kitap, etrafa dağılmış bilginin bir yere toplanmış hali

+ *yazılım geliştirme* ve *programlama* aynı şey değildir

+ *yazılım inşası*, yazılım geliştirme alanındaki bazı konuları içinde barındıran özelleşmiş bir alt daldır. yazılım inşası'nın (construction) dokunuğu dallar:

  1. coding and debugging
  2. unit testing
  3. detailed design
  4. integration
  5. construction planning

+ construction terimi, *programlama* termine benzemektedir.

+ construction'ın yazılım konusunda yaptığı işler:

  1. kodun temelini oturtmak
  2. kodun nasıl test edileceğini belirlemek
  3. sınıfları tasarlama ve yazmak
  4. değişkenleri oluşturmak ve isimlendirmek
  5. kontrol yapılarının seçimi ve kod bloklarının organizasyonunu sağlamak
  6. unit test, integrasyon test ve debug yapmak
  7. varsa diğer takım üyelerinin kodunu incelemek ve kendi kodunun incelemesine izin vermek
  8. koda yorum satırı eklemek ve dikkatli bir şekilde organize etmek/formatlamak
  9. üçüncü parti yazılımları, koda entegre etme
  10. koda ince ayar yaparak daha hızlı çalışmasını ve daha az memory yemesini sağlamak

+ construction'ın dışında kalan alanlar

  1. yönetim
  2. gereksinim geliştirme
  3. yazılım mimarisi
  4. kullanıcı arayüzü tasarımı
  5. sistem testi

+ construction, boyuta bağlı olarak, bir yazılım projesinin %30 veya %80'ini kaplayabilir

+ mimari ve gereksinimler, construction'dan önce gerçekleşen şeylerdir. bu sayede construction çok daha hızlı ve verimli bir şekilde ilerler

+ kaynak kodu, construction evresinin bir ürünüdür. zamanla beraber, gereksinim ve dizayn dökümanları güncelliğini yitirse dahi kaynak kodu her zaman güncel kalır.

* bölüm 2 - yazılım geliştirme metaforları
+ çok iyi anlamadığımız şeyleri bazen çok iyi bildiğimiz bir şeylerle ilişkilendirdiğimizde yani *metafor* kullandığımızda, olayı *modellemiş* oluruz ve daha iyi anlamış oluruz

+ kitapta yazılım geliştirme için kullanılan metafor ise *ev inşaatı*

+ mesela köpeğin için bir kulube yapmaya kalkarsak, ihtiyacımız olan sadece bir kaç tahta ve çivi. kulube bittiğinde eğer bir şeyleri yanlış yaptıysak, bu çok büyük bir sorun teşkil etmez. ya var olan kulubeyi alıp üzerinde oynamalar yaparak düzeltiriz ya da onun yerine yeni bir kulube yapabiliriz.

+ yukarıdaki metafor, yazdığımız küçük kodlar/projeler için de geçerlidir. program düzgün çalışmıyorsa ya üstünde oynama yapar düzeltmeye çalışırız ya da sil baştan yeni bir tane yazarız

+ daha büyük bir ev yapmak istediğimizde ise metaforu genişletmemiz gerekir:

  1. nasıl bir ev yapmak istiyoruz? : *problemi anlamak*
  2. mimar bir tasarım yapar : *yazılım mimari dizaynı*
  3. evin planının çıkarılması : *detaylı yazılım tasarımı*
  4. evin inşası : *yazılım tasarımının kodlanması*
  5. bahçınavlar, boyacılar gelip etrafı güzelleştirir: *optimizasyon*

* Bölüm 3
- yazılım inşasından önce planlama ve dizayn çok önemli bir rol oynar

- Yazılım Geliştirme sacede _kod yazmak değildir_

- WISCA sendromu: "Why Isn't Sam Coding Anymore?"

- WIMP sendromu: "Why Isn't Mary Programming"

- Eğer patronun gerizekalıysa ve her hangi bir dizayn ya da mimariden yoksun bir biçimde kod yazmayı istiyorsa, eski bir projeyi aç ve yan pencerede dizayn ve mimarini yap. Bu sayede hem sen hem de gerizekalı patronun huzurlu bir şekilde hayatına devam eder

- hayat, etrafta daha iyi alternatifler varken cahil bir patronla çalışmak için çok kısa. işi bırak ve başka şirket bul

- bir yazılım geliştirme sürecine farklı bir bakış;
  a. mimar + requirements = *mimari*
  b. dizayner + mimary = *dizayn*
  c. programcı + dizayn = *program*

- yukarıda görüldüğü gibi, program, zincirin en sonundadır. Bu demek oluyor ki, iyi bir programın ortaya çıkması için dizayın iyi yapılması, dizaynın iyi yapılması için de mimarın işini iyi yapması gerekir. _yani aslında yazılımın kaliteli mimarın elindedir_
