#+TITLE: Operating Systems From 0 To 1
#+STARTUP: overview

* Chapter 1 - 3
+ I annoteted the pdf file with the most important informations
+ *computer architecture* = *ISA* + *Computer Organization* + *hardware*
+ ISA has two types: *RISC* and *CISC*
+ Computer Organization has two types: *Von Neuman* and *Harward*
+ both _AMD_ and _Intel_ CPUs has the same ISA (x86) but has different Computer Org.

* Chapter 4: x86 Assembly and C
+ *read* volue 2, section 1.3 in Intel Manual. _exclude 1.3.5 and 1.3.7_
+ normally x86 can address one byte at a time but it can also address more than one bytes in memory. it is called **Segment Addressin**. it helps to organize sections in memory. for example a program can keep its *code* and *segment* sections separated.
+ some of important exceptions are **PF**(page fault) and **GP**(general protection)
+ Using the *bin* format puts *nasm* by default into *16-bit* mode.  To enable 32-bit code to be generated, we must add this line at the be- ginning of an nasm source file: *bits 32*
+ in the *intel instruction reference manual* volume 2 chapter 3 every instruction is documented.
