[[main]]
  identifier = "about"
  name = "~/about"
  url = "about"
  weight = 1

[[main]]
  identifier = "projects"
  name = "~/projects"
  url = "projects"
  weight = 2

[[main]]
  parent = "projects"
  name = "zenith"
  url = "projects/zenith"

[[main]]
  parent = "projects"
  name = "wk"
  url = "projects/wk"

[[main]]
  parent = "projects"
  name = "xkarna"
  url = "projects/xkarna"

[[main]]
  identifier = "notes"
  name = "~/notes"
  url = "notes"
  weight = 3

[[main]]
  parent = "notes"
  name = "languages"
  url = "notes/languages"

[[main]]
  parent = "notes"
  name = "tools"
  url = "notes/tools"

[[main]]
  parent = "notes"
  name = "concepts"
  url = "notes/concepts"

[[main]]
  parent = "notes"
  name = "linux"
  url = "notes/linux"

[[main]]
  parent = "notes"
  name = "electronics"
  url = "notes/electronics"

[[main]]
  identifier = "books"
  name = "~/books"
  url = "books"
  weight = 4

[[main]]
  identifier = "posts"
  name = "~/posts"
  url = "posts"
  weight = 5

[[main]]
  identifier = "music"
  name = "~/music"
  url = "music"
  weight = 6
