[[main]]
  identifier = "about"
  name = "~/about"
  url = "about"
  weight = 1

[[main]]
  identifier = "projects"
  name = "~/projects"
  url = "projects"
  weight = 2

[[main]]
  identifier = "notes"
  name = "~/notes"
  url = "notes"
  weight = 3

[[main]]
  identifier = "books"
  name = "~/books"
  url = "books"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "Cartoon"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "Photo"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 5

[[main]]
  identifier = "showcase"
  name = "Showcase"
  url = "showcase"
  weight = 6

[[main]]
  identifier = "publication"
  name = "Pub"
  url = "publication"
  weight = 7
